CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  uniquid VARCHAR(255) NOT NULL,
  user_name VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(20) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);